# Generated by Django 4.0.3 on 2022-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('pla', models.FloatField(default=0.0)),
                ('udid', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
