# Generated by Django 2.2 on 2022-04-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_db_env_case'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB_env_case',
            new_name='DB_env_script',
        ),
    ]
