# Generated by Django 2.2 on 2022-04-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_db_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('value', models.TextField(default='{}')),
            ],
        ),
    ]
