# Generated by Django 2.2 on 2022-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_db_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_cases',
            name='ifut',
            field=models.BooleanField(default=True),
        ),
    ]
